### ISSUE TITLE
Разработка GTK интерфейса

### ISSUE THREAD

**Issue by HaliksaR** [HaliksaR/WordEng#2]
Построение шаблона с помощью xml и css и написание сигналов для взаимодействия с элементами.

**Comment by HaliksaR** [comment]
# DONE 20%
![Uploading Peek 2018-04-22 21-50.gif…](https://lh3.googleusercontent.com/yvZNwdlqTY1Z5Hnj7LwK3fnq3ajwkaS2BqgoXWUv4sG0_xUDHQzg28CEPKm-sEjFGYGR-7XOCSXrghXLfsFRiMWej4WQvlVLn76lny59PEceTMt0k6ioNQrjec8-2N8I49OSBy8dGVPZ0-2VJRZ5XPQ0WXEsXHoy-qKzlYMRPP9PN2VcQPSDVsrY2nWuo_uRigRe4ECcWj3W8AnjnqnjgjFhabuH5MKhTJLz304_RI60Z1b2iAKzOWDMasRJ6zHeYhRZyUYKaehIZdSgtbI1XSljeySt3dMtWgODbOYQp956NXv-b-5CPDmb7EqCqJRFUxwOiBEopkCJmHQQHCvKwegAzhMpqhqkwaICNQ9c0s1FGPAmi_RnoNzAEAjUBafcWpbjCPrl8OTzqPy7LNYm-i8i2_QCFuqsmXi0BpAVK0TGe2j1If7kE6z1jLT5Okik_DL-YV-ZDkhhFtThWLH7VYIOjogKprUl3h8-VoE7JbaT5fkccUFprcXFSoghekWl-MbRJJQx8dECGGre9ORmssUpEp9gQqg5jLRJI0gMS1_DsK8hPDzrSnLgHW3RGFkHbE_htzSlfzU57nOO_rwweozBobUMX-5qaHL5OGtfeUos53dRWEy7N_YXKx3BYLZBpVBJxPtV2iLxdYVoNlthIV3k9zJzeIL0=w715-h864-no)

**Comment by HaliksaR** [comment]
# DONE 40%

**Comment by HaliksaR** [comment]
# DONE 50%
![Uploading Peek 2018-04-27 16-33.gif…](https://lh3.googleusercontent.com/8Zz04DgkxhyBvaCQ6tfPiTX-YEefXurUyJC_MK7icMTgGyo7jpQPFmoCyqMuNJZgPsGSqnWN3LBj2OkJewHfNNarOTwrKB5CCnliXRfVWV5Vns7YLi0L6K_kgFGVMmfQOj14aY5ttJpkkQ9dxaHZTR-UDWilIagQNjBmhnNiGC1NQLHux_9sQag0Y5YPwUrpPIcBIQlcZbf7VuiKGk7hylePluVVMys_-FY8KVixeV2jvba-X1hB3rcoPvtoExGmEZbyG3kQ7hhOCXr-SrkmMiWrfgSZGpOQK0UrkPyyow0HNOn7fftlZ7tjwg4QOXoiNq_UYd8qknAcHNdVb-b7tA13G9qPVP15T_1oTf2ldxsrg6BTi1ywqlYvax18UCAVpRXL-gZpi4jJLiYHA6vFfHtsuAZbGIShLrjhAX_hk3GzB58S5xaMBQ8im153vsosSNG1EvRXeke38m-8OSp9VztVuHEByKhr91i0GtNIUEPnwVjH4l8qQMYw9HZb0ZgrnSL78ZU_xxs9vvlFC4256avAe7PGGHiLpYRFV3rIh7yccicIylIMfLN2yKmGXvetf3cvCaxjLJRBaSWZB9Qaj7e0MHHieQCEFspivjA=w1094-h932-no)

**Comment by HaliksaR** [comment]
# DONE 70%
![Uploading Peek 2018-04-28.gif…](https://lh3.googleusercontent.com/uU59hJouj87Bp1Qva88blOlTof2bD-O22P3vAN7V9REH3SWr6fPtcUxSkhdGfQdXSQkgmxEN4t1UwrMQ0KEMcOPjHdejXDmua9hu0gnrVIH9tLfWQvftte91JJ1U0Vp7827HJDyS6U2TJw4vPPvwlTtZWXTq-L81J6P89k-Fv7NoLaqQF17js2wyk3V1afaKei2oLkruoKBMQyubJZroCgbuNfFnB9JATREFJxZOnZZb3u5-wDBMnOrRg8vGjxVoJhzN5sWmGNmldFmlGjgVozxT9huYBGLr9X9uHjiIoKfC2hhsteuRe5-fvPERT2_K0EzRdnteUmNLOXyCil81MQxBYs9SGvSqB36qSPpIerrQRIS2CjfPkMbgSGOWVKWCHQvMDQdIocfnHBl7vg02QF4SNZ8bKnqMJuJK_um6tSLzBL2s5Og4GwxP5xoVrwAqzNTqqKOETMjj_iL20rgJn6UYY-XczXHo_GuwlSm6TNgZd_wAMdVp8KXUFh7VBwzqAs2QOrMDLpHlgKR-A9xw3wRO6YlGm6A4kTEZ92qGYLr5QoY2CuGk3chcEHcfc0Uw7Q7wyzH_imb-WqbSqCufZaWA4-XFvVeKtGUscRg=w1178-h956-no)

**Comment by perkthefox** [comment]
фешн из май профешн 💯

**Comment by HaliksaR** [comment]
![x2hesre6w3s](https://user-images.githubusercontent.com/35256960/39398205-ef5c96ae-4b34-11e8-808c-89a629199bef.jpg)

**Comment by HaliksaR** [comment]
# DONE 100%
Осталось корректное подключение тела и фиксация недочетов
