### ISSUE TITLE
Разработка функций для отрисовки консольного интерфейса

### ISSUE THREAD

**Issue by HaliksaR** [HaliksaR/WordEng#4]
Разработка функций для отрисовки консольного интерфейса. Использование цветов и обновления экрана.

**Comment by HaliksaR** [comment]
DONE ~85%

**Comment by artemka13722** [comment]
65% done

**Comment by HaliksaR** [comment]
![vxvkmh4dlia](https://user-images.githubusercontent.com/35256960/39409511-d24eac80-4c12-11e8-8125-2c519f3299ee.jpg)
